// tool/generate_freezed_equatable.dart
//
// Usage:
// dart run tool/generate_freezed_equatable.dart <input.json> <RootClassName> [--existing=key=importPath:Type,...]
//
// Example:
// dart run tool/generate_freezed_equatable.dart tool/sample.json User --existing=profile=lib/models/profile.dart:Profile

import 'dart:convert';
import 'dart:io';
import '../create_auto_files/path_constants.dart';
import '../utils_spinner.dart';

String capitalize(String s) => s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);
String classNameFromKey(String key) {
  final cleaned = key.replaceAll(RegExp(r'[^A-Za-z0-9]'), '');
  final candidate = cleaned.isEmpty ? 'Auto' : cleaned;
  return capitalize(candidate);
}

final Map<String, Map<String, dynamic>> classes = {};
final Map<String, Map<String, String>> existingTypes = {};
final Set<String> imports = {};

void parseExistingArg(String arg) {
  // arg format: key=importPath:Type,key2=importPath2:Type2
  final pairs = arg.split(',');
  for (final p in pairs) {
    final eq = p.indexOf('=');
    if (eq <= 0) continue;
    final key = p.substring(0, eq).trim();
    final rest = p.substring(eq + 1).trim();
    final colon = rest.lastIndexOf(':');
    if (colon <= 0) continue;
    final importPath = rest.substring(0, colon).trim();
    final typeName = rest.substring(colon + 1).trim();
    if (key.isNotEmpty && importPath.isNotEmpty && typeName.isNotEmpty) {
      existingTypes[key] = {'import': importPath, 'type': typeName};
      imports.add(importPath);
    }
  }
}

void infer(Map<String, dynamic> map, String className) {
  final fields = <String, dynamic>{};
  map.forEach((k, v) {
    if (v == null) {
      fields[k] = null;
    } else if (v is int) {
      fields[k] = 'int';
    } else if (v is double) {
      fields[k] = 'double';
    } else if (v is bool) {
      fields[k] = 'bool';
    } else if (v is String) {
      fields[k] = 'String';
    } else if (v is Map<String, dynamic>) {
      if (existingTypes.containsKey(k)) {
        final info = existingTypes[k]!;
        fields[k] = info['type'];
        imports.add(info['import']!);
      } else {
        final nestedName = classNameFromKey(k);
        fields[k] = nestedName;
        if (!classes.containsKey(nestedName)) {
          classes[nestedName] = {};
          infer(v, nestedName);
        }
      }
    } else if (v is List) {
      if (v.isEmpty) {
        fields[k] = 'List<dynamic>';
      } else {
        final first = v.first;
        if (first is Map<String, dynamic>) {
          final singularKey = k.replaceAll(RegExp(r's$'), '');
          if (existingTypes.containsKey(singularKey)) {
            final info = existingTypes[singularKey]!;
            fields[k] = 'List<${info['type']}>';
            imports.add(info['import']!);
          } else {
            final nested = '${classNameFromKey(singularKey)}Item';
            fields[k] = 'List<$nested>';
            if (!classes.containsKey(nested)) {
              classes[nested] = {};
              infer(first, nested);
            }
          }
        } else if (first is int) {
          fields[k] = 'List<int>';
        } else if (first is double) {
          fields[k] = 'List<double>';
        } else if (first is bool) {
          fields[k] = 'List<bool>';
        } else if (first is String) {
          fields[k] = 'List<String>';
        } else {
          fields[k] = 'List<dynamic>';
        }
      }
    } else {
      fields[k] = 'dynamic';
    }
  });

  classes[className] = fields;
}

String dartTypeFor(dynamic raw) {
  if (raw == null) return 'dynamic';
  return raw.toString();
}

String generateFreezedEquatable(String fileName,String className) {
  final buffer = StringBuffer();
  buffer.writeln('// GENERATED BY tool/generate_freezed_equatable.dart — DO NOT EDIT');
  buffer.writeln("import 'package:freezed_annotation/freezed_annotation.dart';");
  buffer.writeln("import 'package:equatable/equatable.dart';");
  for (final imp in imports) {
    buffer.writeln("import '$imp';");
  }
  buffer.writeln('');
  buffer.writeln("part '$fileName.freezed.dart';");
  buffer.writeln("part '$fileName.g.dart';\n");

  // deterministic order: root first
  final ordered = <String>[];
  ordered.add(className);
  for (final k in classes.keys) {
    if (k != className) ordered.add(k);
  }

  for (final cls in ordered) {
    // skip generation if this class is provided as an existing type
    final isExisting = existingTypes.values.any((m) => m['type'] == cls);
    if (isExisting) continue;

    final fields = classes[cls]!;

    buffer.writeln('@freezed');
    buffer.writeln('class $cls with _\$$cls, EquatableMixin {');
    buffer.writeln('  const $cls._();'); // <-- private constructor required by freezed
    if (fields.isEmpty) {
      buffer.writeln('  const factory $cls() = _$cls;\n');
    } else {
      buffer.writeln('  const factory $cls({');
      fields.forEach((name, type) {
        final t = type == null ? 'dynamic' : dartTypeFor(type);
        buffer.writeln('    required $t $name,');
      });
      buffer.writeln('  }) = _$cls;\n');
    }
    buffer.writeln('  factory $cls.fromJson(Map<String, dynamic> json) => _\$${cls}FromJson(json);\n');

// Equatable props
    buffer.writeln('  @override');
    buffer.writeln('  List<Object?> get props => [');
    fields.forEach((name, type) {
      buffer.writeln('    $name,');
    });
    buffer.writeln('  ];\n');

    buffer.writeln('}\n');

  }

  return buffer.toString();
}


Future<void> main(List<String> args) async {
 final Spinner spinner = Spinner('🧰 Running Model Creator...');
  spinner.start();
  if (args.isEmpty) {
    spinner.stop('Usage: dart run tool/generate_freezed_from_map.dart <input.json> <RootClassName> [--existing=key=import:Type,...]');

    exit(1);
  }

  final className =  args[0] ;
  final screenName =  args[1] ;
  final String inputPath='lib/core/tools/model_creation/data.json';
  final modelFolderPath =  "lib/features/screens/$screenName/data/model" ;

  final inputFile = File(inputPath);
  if (!  Directory(modelFolderPath).existsSync()) {
  // if (!await File(modelFolderPath).exists()) {
    spinner.stop('model folder not found: $modelFolderPath');
    exit(2);
  }

  if (!await inputFile.exists()) {
    spinner.stop('Input file not found: $inputPath');
    exit(2);
  }

  final content = await inputFile.readAsString();
  dynamic map;
  try {
    map = json.decode(content);
  } catch (e) {
    spinner.stop('Failed to parse JSON: $e');
    exit(3);
  }

  if (map is! Map<String, dynamic>) {
    spinner.stop('Top-level JSON must be an object (Map<String, dynamic>).');
    exit(4);
  }

  classes.clear();
  imports.clear();
  // keep imports from existingTypes
  for (final v in existingTypes.values) {
    imports.add(v['import']!);
  }

  infer(map, className);


  final String fileName=className .
  replaceAllMapped(RegExp(r'(?<!^)([A-Z])'), (Match m) => '_${m.group(0)}') .toLowerCase();
  final outDir = Directory('$modelFolderPath/$fileName');
  await outDir.create(recursive: true);
  final outFile = File('${outDir.path}/$fileName.dart');
  final code = generateFreezedEquatable(fileName,className);
  await outFile.writeAsString(code);

  print('Wrote ${outFile.path}');
  if (args.contains('--no-build')) {
    spinner.stop('Model file created. Skipping build_runner as requested.');
    return;
  }

  stdout.write('Do you want to continue [Y/N]: ');
  final input = stdin.readLineSync(encoding: utf8)?.trim().toLowerCase() ?? '';

  if (input.isEmpty || input == 'n' || input == 'no') {
    spinner.stop('Aborted by user.');
    exit(0);
  }

  if (input == 'y' || input == 'yes') {

    stdout.write('Do you want generate only for this model [Y/N]: ');
    final input = stdin.readLineSync(encoding: utf8)?.trim().toLowerCase() ?? '';
     List<String>additionalArg=[];
    if ( input.toLowerCase() == 'y' || input.toLowerCase() == 'yes') {
      final String  relativePath = '${outDir.path}/$fileName';
      additionalArg=[
        '--build-filter=$relativePath.g.dart',
        '--build-filter=$relativePath.freezed.dart',

      ];
    }



    print('Running build_runner...');
    final process = await Process.start(
        'flutter',
        ['pub', 'run', 'build_runner', 'build','--delete-conflicting-outputs',...additionalArg],
        runInShell: true);
    process.stdout.transform(const SystemEncoding().decoder).listen(print);
    process.stderr.transform(const SystemEncoding().decoder).listen(print);

    await process.exitCode;

    spinner.stop();
  }else{
    // If user typed something else, treat as abort
    spinner.stop('Unrecognized input. Aborted.');
    exit(0);
  }


}
